version: '3.7'

services:

  db:
    container_name: db_postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - webflux_data:/var/lib/postgresql/data

volumes:
  webflux_data:
